### ISSUE TITLE
How to modify example code to use ECDSA (CGGMP) ?

### ISSUE THREAD

**Issue by Hoodie-Kang** [getamis/alice#229]
Hi I want to use ECDSA(especially CGGMP) by modifying example code.

First I have handled DKG part of ECDSA(CGGMP).

So I did modified import "tss/dkg" to "tss/ecdsa/cggmp/dkg in these files: dkg/config.go, dkg/main.go, dkg/service.go, utils/utils.go, main.go

And added "sid" to function NewService in dkg/service.go

```
func NewService(config *DKGConfig, pm types.PeerManager) (*service, error) {
	s := &service{
		config: config,
		pm:     pm,
		done:   make(chan struct{}),
	}

	sid := make([]byte, 1)
	d, err := dkg.NewDKG(utils.GetCurve(), pm, sid, config.Threshold, config.Rank, s)
	if err != nil {
		log.Warn("Cannot create a new DKG", "config", config, "err", err)
		return nil, err
	}
	s.dkg = d
	return s, nil
}
```

Then each participant of 3-3 dkg didn't proceed after "successfully connect to peer" twice while running.

So I want to ask you how to use ECDSA(CGGMP) in a better(correct) way.

Thank you in advance!

**Comment by Hoodie-Kang** [comment]
By the way, above example code can make results if I run 2 of 2 dkg by modifying input configs.

Both of participants printed "Dkg done" and the outputs are:

id-10001-output.yaml
```
share: "31052753871736976167367317859512765276470989393721063383654803743066679453480"
pubkey:
  x: "25162917454634828525931633151091237546031943092514853666542491015960663317625"
  "y": "101256400736787412054306611223984329509651679357502392081040131003103006022268"
bks:
  id-10001:
    x: "110089849653815658980153180871419064956426392606623089146496719192121591356393"
    rank: 0
  id-10002:
    x: "112501917392551893599354948290685384227906645237236634177329431429194935346366"
    rank: 0
rid:
- 81
- 161
- 219
- 79
- 6
- 25
- 226
- 93
- 85
- 62
- 54
- 170
- 72
- 225
- 240
- 80
- 66
- 96
- 190
- 85
- 101
- 145
- 72
- 120
- 246
- 38
- 158
- 172
- 131
- 164
- 87
- 109
```

id-10002-output.yamle
```
share: "31052753871736976167367317859512765276470989393721063383654803743066679453480"
pubkey:
  x: "25162917454634828525931633151091237546031943092514853666542491015960663317625"
  "y": "101256400736787412054306611223984329509651679357502392081040131003103006022268"
bks:
  id-10001:
    x: "110089849653815658980153180871419064956426392606623089146496719192121591356393"
    rank: 0
  id-10002:
    x: "112501917392551893599354948290685384227906645237236634177329431429194935346366"
    rank: 0
rid:
- 81
- 161
- 219
- 79
- 6
- 25
- 226
- 93
- 85
- 62
- 54
- 170
- 72
- 225
- 240
- 80
- 66
- 96
- 190
- 85
- 101
- 145
- 72
- 120
- 246
- 38
- 158
- 172
- 131
- 164
- 87
- 109
```

Is this result correct?
