### ISSUE TITLE
PartialPubKeys are not same after Refresh of CGGMP

### ISSUE THREAD

**Issue by Hoodie-Kang** [getamis/alice#231]
Hi all,

Thanks to support of @cychuang0924, I made a result of 2-2 Refresh.

But the partialpubkeys of the outputs were not same. 
I think that's because the partialpubkey derived from tempSum and pt.ScalarBaseMult(curve, refreshShare) are different(in the refresh/round_3.go)

Why are they different? How can I make the same results? 

The inputs:

id-10001-input.yaml
```
port: 10001
threshold: 2
peers:
  - 10002
share: "4433930311896586173225605911604098714764809986765287553545688226619194396795"
pubkey:
  x: "112363345206559513967411659444620105992871732728134049791505159850234274012554"
  "y": "90435951029605018774762791226409664020987295549738711287286651149053644515432"
bks:
  id-10001:
    x: "35708105979892983394462002592936921792160460602972875353936833272812615304178"
    rank: 0
  id-10002:
    x: "69597477371637251385786663792575032001854147985881576910239092372529440542030"
    rank: 0
partialPubKey:
  id-10001:
    x: "15849057758074928043515211951663352407197755444989195243410918429833618542370"
    "y": "58014041619361282124176111841371497990822144823978969956687650143065582384198"
  id-10002:
    x: "90754768906026963700444021335536463822976573633330741318587490742651816111021"
    "y": "96757763996547835948860220572286724726844536685329626500887151307425848182277"
ssid: ...
```

id-10002-input.yaml
```
port: 10002
threshold: 2
peers:
  - 10001
share: "11206683307503035256881204936677301873389877738402403164108038906992854558074"
pubkey:
  x: "112363345206559513967411659444620105992871732728134049791505159850234274012554"
  "y": "90435951029605018774762791226409664020987295549738711287286651149053644515432"
bks:
  id-10001:
    x: "35708105979892983394462002592936921792160460602972875353936833272812615304178"
    rank: 0
  id-10002:
    x: "69597477371637251385786663792575032001854147985881576910239092372529440542030"
    rank: 0
partialPubKey:
  id-10001:
    x: "15849057758074928043515211951663352407197755444989195243410918429833618542370"
    "y": "58014041619361282124176111841371497990822144823978969956687650143065582384198"
  id-10002:
    x: "90754768906026963700444021335536463822976573633330741318587490742651816111021"
    "y": "96757763996547835948860220572286724726844536685329626500887151307425848182277"
ssid: ...
```

The output:
id-10001-output.yaml
```
share: "59671725594357204030044163484038611929433769768154946216574583106603966142"
partialPubKey:
  id-10001:
    x: "88133999358853328508051570368843532962898058726668892788737128454712963918054"
    "y": "87846378434548133821923717044446705408690277502487790164460985950911948700568"
  id-10002:
    x: "61854933971624880565020130234110533508799567992515778949170006511501217810674"
    "y": "77012160953119353852637882041058487551232336638515226747625596259107884832753"
...
```

id-10002-output.yaml
```
share: "49313068955655674938700182337946476684177761702886598765707079814552104403759"
partialPubKey:
  id-10001:
    x: "86663065689027239141370891757580667742533112958708787560381562997882597061763"
    "y": "86226022784213947809680056832636734039772048902167348368743614461674663658617"
  id-10002:
    x: "5260811651159430176626688247073021814760514716438390505475260537195784942993"
    "y": "70494044436602668890606423764246233923814272908588849230964510092860447088197"
...
```

Thank you!
