### ISSUE TITLE
Question about the compatibility of BIP 32

### ISSUE THREAD

**Issue by Hoodie-Kang** [getamis/alice#233]
Hi

The Signer in example, which uses GG18, needs inputs including BKs and Shares.
Also the Sign of CGGMP needs inputs including shares, partial publickeys,  bks, ssid, etc.

The master in bip32 outputs including BKs and shares so it can be used as an input of signer of GG18, but can't be an input of sign of CGGMP because it need so many other information.
Moreover the child in bip32 outputs shares without BKs, so it cannot be used as an input of any sign protocols.

So here is the question,
how can I use the outputs of bip32 to sign following CGGMP and GG18?
In detail, how can I make other necessary information including BKs to fit in the form of inputs of both Signs?

Thanks

**Comment by cychuang0924** [comment]
Hi Hoodie-Kang,

The BIP32's protocol only supports GG18.
The BKs of the child in BIP32 is inherited from the master in BIP32.
So, you have sufficient information to perform the sign of GG18.

About supporting CGGMP, it needs some other extra informations, this is a good feature.
If we have free time, we will implement it.
If you plan to do it yourself, you only generate the "ssid" in the master key generation of BIP32.
Here ssid := A's ssid  xor B's ssid, which is the same formula in CGGMP.
Partial public is each party's share multiplying G (i.e. s_i*G).
Then you have the same outputs as DKG of CGGMP.
Next, you run the protocol of Refresh, then you can get Paillier's keys.
The child of BIP32 also uses the same information rid, Paillier's keys and BKs.

By the way, you can use the same pattern of ssid as CGGMP (ref. Figure5:  interpret sid = (. . . , G, q, g, P )).

If you have any question, please let me know. Thanks.
By the way, we have a new version of BIP32, which is safer. But we only offers a POC.
ref: https://github.com/getamis/alice/tree/AddMoreCircuit/crypto/bip32

**Comment by Hoodie-Kang** [comment]
Hi cychuang,

> The BKs of the child in BIP32 is inherited from the master in BIP32.
Does it mean the BKs of the child is same as the master's BKs, right?
So I put the BKs of the master , shares and pubkey of the result of child as inputs of the example Signer(supporting GG18),
but it printed below message.

```
INFO [01-30|10:02:47.680|message/msg_main.go:158] Change handler                           self=id-10002 msgType=1 fromId=id-10001 oldType=1 newType=2
WARN [01-30|10:02:47.704|signer/2_mta_handler.go:148] Unexpected public key                    self=id-10002 msgType=2 fromId=id-10001 exp="(x, y) =(60576254043948321120504991537465487157539913427948814188331348936263773203325, 88384804550390943077059257609818049928488659130969924780324346745171253123515)" got="(x, y) =(76236163921266583450921844951100146922464693447228813856081827815144078948682, 75535945727547807292640298370683079821929120364109987677535374452367689764615)"
WARN [01-30|10:02:47.704|message/msg_main.go:148]     Failed to go to next handler             self=id-10002 msgType=2 fromId=id-10001 err="unexpected public key"
INFO [01-30|10:02:47.704|message/msg_main.go:170]     State changed                            self=id-10002 old=Init new=Failed
ERROR[01-30|10:02:47.704|signer/service.go:102]       Signer failed                            old=Init new=Failed
```

Here are the inputs
```
share: "19314912191000541419872535925495115820644180555311607129040775338216522949679"
pubkey:
  x: "60576254043948321120504991537465487157539913427948814188331348936263773203325"
  "y": "88384804550390943077059257609818049928488659130969924780324346745171253123515"
bks:
  id-10001:
    x: "30037029816804127442838158252133331904516252338214806492403523861880278689988"
    rank: 0
  id-10002:
    x: "96578854112514857777221530994821975964494790946865720905808190272899481450178"
    rank: 0
msg: "child sign"
```
```
share: "66808307081423988966705308530915318122562404687876906911229251682513508041591"
pubkey:
  x: "60576254043948321120504991537465487157539913427948814188331348936263773203325"
  "y": "88384804550390943077059257609818049928488659130969924780324346745171253123515"
bks:
  id-10001:
    x: "30037029816804127442838158252133331904516252338214806492403523861880278689988"
    rank: 0
  id-10002:
    x: "96578854112514857777221530994821975964494790946865720905808190272899481450178"
    rank: 0
```

However, the sign using master result works well.
So I think something goes wrong, but I don't have any idea :(
How can I make it work?

Thank you,

Hoodie
