### ISSUE TITLE
Different Public key issue when Signing Ethereum Raw Transaction

### ISSUE THREAD

**Issue by Hoodie-Kang** [getamis/alice#236]
Hi

I'm trying to send a raw transaction in the Goerli Ethereum test net using Web3.js.
Here is the transaction data and the hash of the transaction.

```
{
  nonce: '0x0',
  to: '0x66Cba25faF0a341Fe536925c46687B1160a197a7',
  value: '0x38d7ea4c68000',
  gasLimit: '0x1d8a8',
  gasPrice: '0x4a817c800',
  data: '0x0',
  v: '0x2d',
  r: '0x0',
  s: '0x0'
}
hash: 3a6e0c03fcfd2ac737a2fa8a9535a088469e1f75f323a8377f8355a4103ba00f
```

Using GG18, after 2 of 2 DKG the signer inputs were:
```
port: 10001
peers:
  - 10002
share: "48009635119716801121422388540381921473982761023954328247557439033967871640185"
pubkey:
  x: "10290526619007406802679274811427206866549400507245539291039072171369241278468"
  y: "37504811230942583636922232634339105768466278733205375082142890370196805216860"
bks:
  id-10001:
    x: "9987879638869391180574507371944186878398536146226961513235596770885926708560"
    rank: 0
  id-10002:
    x: "27430016224955743730177942842935577266812994817782174086985731142993166568517"
    rank: 0
msg: "3a6e0c03fcfd2ac737a2fa8a9535a088469e1f75f323a8377f8355a4103ba00f"
```
```
port: 10002
peers:
  - 10001
share: "83571483614016019445058258921935883022592627804235010868567212221454054200457"
pubkey: same
bks: same
msg: same
```

the sign output
```
r: "89604550539853586697799468095878687627444370844130366237671645935096428765871"
s: "102093535849068150100945179871541286901271488417765717028400532673319260928573"
```

I put it in the transaction data and send the transaction.

And here is the problem..

I guess the address of the sender is "0x8B217caa3B2086C8C3769621D9754c11C59b998D"
(ref. https://ethereum.org/en/developers/docs/accounts/ ) 

But when I derive the sender address by using getSenderAddress() in 'ethereumjs-tx', the sender addresses are not same.

I'm very confused :(
Can you help me to find out what the problem is?

Thank you always,
Hoodie

p.s.   Even using CGGMP, above problem also happened ..
p.s.2 I edit msg code as msg, _ := hex.DecodeString(config.Message) because hash of transaction is hex string format
